#!/usr/bin/env python

import os
import sys
import cv

cv.NamedWindow('w1', cv.CV_WINDOW_AUTOSIZE)

cam_index = 0
capture = cv.CaptureFromCAM(cam_index)

frame = cv.QueryFrame(capture)
cv.SaveImage('tmp/isight.jpg', frame)

while True:
    frame = cv.QueryFrame(capture)
    cv.ShowImage('w1', frame)
