#!/usr/bin/env python

import os
import sys
import cv

import detector.face

cv.NamedWindow('w1', cv.CV_WINDOW_AUTOSIZE)

cam_index = 0
capture   = cv.CaptureFromCAM(cam_index)
frame     = cv.QueryFrame(capture)

detector = detector.face.Face()
detector.detect(frame)
