#!/usr/bin/env python
import os
import sys
import detector.face

def print_usage():
    print "Usage: race-detect <detector> <imagepath>"

if __name__ == '__main__':
    if not len(sys.argv) == 3:
        print_usage()
        sys.exit(1)

    key   = sys.argv[1]
    image = sys.argv[2]

    detectors = {
                'eye': detector.face.Eye
            }

    try:
        d = detectors[key]
        d().detect(image)
    except KeyError:
        print "Invalid detector: %s" % key
        print_usage()
        sys.exit(1)
